"""initial_tables

Revision ID: dfed1d51bef1
Revises: 
Create Date: 2020-04-18 16:55:14.563049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfed1d51bef1'
down_revision = None
branch_labels = None
depends_on = None

from alembic import context

def check_is_sqlite(): 
    """Returns if the alembic context is being run in for a sqlite db""" 
    databaseUri = context.config.get_main_option('sqlalchemy.url') 
    return databaseUri.startswith('sqlite')

ADDITIONAL_ARGS = { 'schema': 'construction_projects' }


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if check_is_sqlite(): 
        ADDITIONAL_ARGS.pop('schema')
    else: 
        op.create_schema(ADDITIONAL_ARGS['schema'])
        
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('ts_created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    **ADDITIONAL_ARGS
    )

    op.create_table('upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.Column('source_filename', sa.String(), nullable=False),
    sa.Column('ts_uploaded', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id_project', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_project'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath'),
    **ADDITIONAL_ARGS
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload')
    op.drop_table('project')
    # ### end Alembic commands ###
